### PR TITLE
a few edits, and comments in html comments

### PR DESCRIPTION
**Pull request by sckott**
looks great!

wish i was doing this for the meta-analyses i worked on!

### CODE REVIEW

**Comment by dfalster** [comment]
Thanks so much for feedback Scott. Have pushed up a few minor changes. If you're happy it's ready to go!

**Comment by sckott** [comment]
Yes, happy.  Going to post anywhere else?  If so, should I wait until that is up, or do at same time, etc.

**Comment by richfitz** [comment]
No, we're just going with ropensci, as our blog is somewhat dormant at the moment...

**Comment by dfalster** [comment]
I'll also post a link from my blog, linking to ropensci page, once it's up. So go for it Scott.

**Comment by sckott** [comment]
Awesome, will post tomorrow am

**Comment by richfitz** [comment]
Thanks Scott! :rocket::koala::shipit:

**Pull request merged**
